---
- name: Instalar Nginx
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Actualizar caché de paquetes
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Instalar Nginx
      package:
        name: nginx
        state: present
