---
- name: 1. Asegurar que Ansible esté instalado
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Instalar Ansible
      yum:
        name: ansible
        state: present
      when: ansible_os_family == "RedHat" or ansible_distribution == "Amazon"

    - name: Instalar Ansibl
      apt:
        name: ansible
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

- name: 2. Instalar Nginx
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Instalar Nginx
      package:
        name: nginx
        state: present
